max_epochs: 100
gradient_clip_val: 0.5
num_sanity_val_steps: 2
accumulate_grad_batches: 4
precision: 16-mixed
log_every_n_steps: 5
accelerator: gpu
enable_progress_bar: True
reload_dataloaders_every_n_epochs: 5
